[2022-01-18 15:58:19,463 INFO @src.logger.base_logger] 19 - Running script at src.train
[2022-01-18 15:58:19,466 ERROR @src.logger.base_logger] 25 - The script halted with an error
Traceback (most recent call last):
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/main.py", line 21, in run
    mod = importlib.import_module(mod_name)
  File "/home/doni-lab-ai/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/train.py", line 3, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
[2022-01-18 15:58:33,955 INFO @src.logger.base_logger] 19 - Running script at src.train
[2022-01-18 15:58:35,992 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 15:58:36,002 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 15:58:36,556 DEBUG @src.logger.base_logger] 23 - Detected device: cuda
[2022-01-18 15:58:36,556 ERROR @src.logger.base_logger] 25 - The script halted with an error
Traceback (most recent call last):
  File "main.py", line 22, in run
    mod.run(args)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/train.py", line 35, in run
    SEED = int(conf['deterministic']['seed'])
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'deterministic'
[2022-01-18 15:59:14,599 INFO @src.logger.base_logger] 19 - Running script at src.train
[2022-01-18 15:59:15,554 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 15:59:15,566 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 15:59:15,931 DEBUG @src.logger.base_logger] 23 - Detected device: cuda
[2022-01-18 15:59:15,933 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 15:59:15,933 INFO @src.logger.base_logger] 51 - CuDNN is enabled: True
[2022-01-18 15:59:15,934 ERROR @src.logger.base_logger] 25 - The script halted with an error
Traceback (most recent call last):
  File "main.py", line 22, in run
    mod.run(args)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/train.py", line 70, in run
    train_loader, valid_loader = setup_cifar10(cifar_path, BATCH_SIZE, NUM_WORKERS)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/data.py", line 31, in setup_cifar10
    train_dataset = torchvision.datasets.CIFAR10(
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torchvision/datasets/cifar.py", line 68, in __init__
    raise RuntimeError('Dataset not found or corrupted.' +
RuntimeError: Dataset not found or corrupted. You can use download=True to download it
[2022-01-18 16:00:24,983 INFO @src.logger.base_logger] 19 - Running script at src.train
[2022-01-18 16:00:25,920 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:00:25,930 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:00:26,243 DEBUG @src.logger.base_logger] 23 - Detected device: cuda
[2022-01-18 16:00:26,244 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:00:26,244 INFO @src.logger.base_logger] 51 - CuDNN is enabled: True
[2022-01-18 16:00:27,331 ERROR @src.logger.base_logger] 25 - The script halted with an error
Traceback (most recent call last):
  File "main.py", line 22, in run
    mod.run(args)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/train.py", line 145, in run
    model = MobileNetV3Module(hparams, rgb_img, mode=args.mode)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 236, in __init__
    self.net = MobileNetV3(self.hparams.num_classes, self.hparams.dropout, self.rgb_img, self.mode)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 163, in __init__
    self.bneck_specs = self.load_bneck_specs()
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 195, in load_bneck_specs
    with open(self.spec_file, "r") as spec_f:
FileNotFoundError: [Errno 2] No such file or directory: '../specification/mobilenetv3-large.json'
[2022-01-18 16:01:14,992 INFO @src.logger.base_logger] 19 - Running script at src.train
[2022-01-18 16:01:15,942 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:01:15,952 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:01:16,257 DEBUG @src.logger.base_logger] 23 - Detected device: cuda
[2022-01-18 16:01:16,258 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:01:16,259 INFO @src.logger.base_logger] 51 - CuDNN is enabled: True
[2022-01-18 16:01:17,338 INFO @pytorch_lightning.utilities.distributed] 1294 - GPU available: True, used: True
[2022-01-18 16:01:17,338 INFO @pytorch_lightning.utilities.distributed] 1297 - TPU available: False, using: 0 TPU cores
[2022-01-18 16:01:17,338 INFO @pytorch_lightning.utilities.distributed] 1300 - IPU available: False, using: 0 IPUs
[2022-01-18 16:01:17,338 INFO @src.logger.base_logger] 153 - Precision: 32
[2022-01-18 16:01:17,338 INFO @src.logger.base_logger] 154 - Train the mobilenetv3 model.
[2022-01-18 16:01:17,403 INFO @src.logger.base_logger] 19 - Running script at src.train
[2022-01-18 16:01:18,364 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:01:18,373 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:01:18,668 DEBUG @src.logger.base_logger] 23 - Detected device: cuda
[2022-01-18 16:01:18,669 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:01:18,669 INFO @src.logger.base_logger] 51 - CuDNN is enabled: True
[2022-01-18 16:01:19,121 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:01:19,127 INFO @pytorch_lightning.plugins.training_type.ddp] 322 - initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
[2022-01-18 16:01:20,063 INFO @src.logger.base_logger] 153 - Precision: 32
[2022-01-18 16:01:20,063 INFO @src.logger.base_logger] 154 - Train the mobilenetv3 model.
[2022-01-18 16:01:20,064 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:01:20,065 INFO @pytorch_lightning.plugins.training_type.ddp] 322 - initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
[2022-01-18 16:01:20,065 INFO @torch.distributed.distributed_c10d] 196 - Added key: store_based_barrier_key:1 to store for rank: 1
[2022-01-18 16:01:20,066 INFO @torch.distributed.distributed_c10d] 196 - Added key: store_based_barrier_key:1 to store for rank: 0
[2022-01-18 16:01:20,067 INFO @torch.distributed.distributed_c10d] 226 - Rank 0: Completed store-based barrier for 2 nodes.
[2022-01-18 16:01:20,067 INFO @pytorch_lightning.utilities.distributed] 328 - ----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All DDP processes registered. Starting ddp with 2 processes
----------------------------------------------------------------------------------------------------

[2022-01-18 16:01:20,076 INFO @torch.distributed.distributed_c10d] 226 - Rank 1: Completed store-based barrier for 2 nodes.
[2022-01-18 16:01:25,199 INFO @pytorch_lightning.accelerators.gpu] 54 - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
[2022-01-18 16:01:25,199 INFO @pytorch_lightning.accelerators.gpu] 54 - LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
[2022-01-18 16:01:25,306 DEBUG @git.cmd] 869 - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:01:25,445 DEBUG @urllib3.connectionpool] 227 - Starting new HTTP connection (1): localhost:8080
[2022-01-18 16:01:25,494 DEBUG @urllib3.connectionpool] 452 - http://localhost:8080 "POST /graphql HTTP/1.1" 200 464
[2022-01-18 16:01:25,502 DEBUG @urllib3.connectionpool] 227 - Starting new HTTP connection (1): localhost:8080
[2022-01-18 16:01:25,522 DEBUG @urllib3.connectionpool] 452 - http://localhost:8080 "POST /graphql HTTP/1.1" 200 368
[2022-01-18 16:01:28,884 INFO @pytorch_lightning.core.lightning] 1736 - 
  | Name          | Type             | Params
---------------------------------------------------
0 | net           | MobileNetV3      | 4.3 M 
1 | criterion     | CrossEntropyLoss | 0     
2 | train_metrics | MetricCollection | 0     
3 | val_metrics   | MetricCollection | 0     
4 | test_metrics  | MetricCollection | 0     
---------------------------------------------------
4.3 M     Trainable params
0         Non-trainable params
4.3 M     Total params
17.142    Total estimated model params size (MB)
[2022-01-18 16:01:35,960 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:01:35,961 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:02:28,110 INFO @pytorch_lightning.callbacks.early_stopping] 267 - [rank: 1] Metric val_Accuracy improved. New best score: 0.100
[2022-01-18 16:02:28,111 INFO @pytorch_lightning.callbacks.early_stopping] 267 - [rank: 0] Metric val_Accuracy improved. New best score: 0.100
[2022-01-18 16:06:35,980 INFO @pytorch_lightning.callbacks.early_stopping] 267 - [rank: 1] Monitored metric val_Accuracy did not improve in the last 5 records. Best score: 0.100. Signaling Trainer to stop.
[2022-01-18 16:06:35,980 INFO @pytorch_lightning.callbacks.early_stopping] 267 - [rank: 0] Monitored metric val_Accuracy did not improve in the last 5 records. Best score: 0.100. Signaling Trainer to stop.
[2022-01-18 16:06:36,155 DEBUG @urllib3.connectionpool] 227 - Starting new HTTP connection (1): localhost:8080
[2022-01-18 16:06:36,165 DEBUG @urllib3.connectionpool] 452 - http://localhost:8080 "POST /graphql HTTP/1.1" 200 58
[2022-01-18 16:06:36,180 INFO @pytorch_lightning.profiler.base] 113 - FIT Profiler Report

Action                             	|  Mean duration (s)	|Num calls      	|  Total time (s) 	|  Percentage %   	|
--------------------------------------------------------------------------------------------------------------------------------------
Total                              	|  -              	|_              	|  318.84         	|  100 %          	|
--------------------------------------------------------------------------------------------------------------------------------------
run_training_epoch                 	|  50.001         	|6              	|  300.01         	|  94.094         	|
run_training_batch                 	|  0.39664        	|588            	|  233.22         	|  73.148         	|
model_forward                      	|  0.37794        	|588            	|  222.23         	|  69.7           	|
training_step                      	|  0.37784        	|588            	|  222.17         	|  69.681         	|
closure_0                          	|  0.25493        	|588            	|  149.9          	|  47.015         	|
get_train_batch                    	|  0.055336       	|588            	|  32.538         	|  10.205         	|
evaluation_step_and_end            	|  0.10271        	|122            	|  12.53          	|  3.93           	|
validation_step                    	|  0.10258        	|122            	|  12.514         	|  3.9251         	|
on_train_epoch_end                 	|  0.033392       	|6              	|  0.20035        	|  0.062838       	|
training_batch_to_device           	|  0.00025432     	|588            	|  0.14954        	|  0.046901       	|
on_train_batch_end                 	|  0.0002386      	|588            	|  0.1403         	|  0.044003       	|
on_after_backward                  	|  8.046e-05      	|588            	|  0.04731        	|  0.014839       	|
on_before_optimizer_step           	|  6.3025e-05     	|588            	|  0.037058       	|  0.011623       	|
evaluation_batch_to_device         	|  0.00027262     	|122            	|  0.03326        	|  0.010432       	|
on_validation_batch_end            	|  0.00021064     	|122            	|  0.025698       	|  0.00806        	|
on_before_backward                 	|  3.4502e-05     	|588            	|  0.020287       	|  0.0063628      	|
on_batch_start                     	|  3.017e-05      	|588            	|  0.01774        	|  0.005564       	|
on_train_batch_start               	|  2.6833e-05     	|588            	|  0.015778       	|  0.0049486      	|
on_batch_end                       	|  2.3624e-05     	|588            	|  0.013891       	|  0.0043567      	|
on_validation_end                  	|  0.0019217      	|7              	|  0.013452       	|  0.0042191      	|
training_step_end                  	|  1.9672e-05     	|588            	|  0.011567       	|  0.0036278      	|
on_train_start                     	|  0.0099764      	|1              	|  0.0099764      	|  0.003129       	|
on_validation_batch_start          	|  4.6256e-05     	|122            	|  0.0056432      	|  0.0017699      	|
on_train_epoch_start               	|  0.00077994     	|6              	|  0.0046796      	|  0.0014677      	|
on_validation_start                	|  0.00060825     	|7              	|  0.0042578      	|  0.0013354      	|
validation_step_end                	|  2.1531e-05     	|122            	|  0.0026268      	|  0.00082386     	|
on_train_end                       	|  0.00066246     	|1              	|  0.00066246     	|  0.00020778     	|
on_epoch_end                       	|  4.4522e-05     	|13             	|  0.00057879     	|  0.00018153     	|
on_validation_epoch_end            	|  6.6254e-05     	|7              	|  0.00046378     	|  0.00014546     	|
on_epoch_start                     	|  3.3295e-05     	|13             	|  0.00043283     	|  0.00013575     	|
on_validation_epoch_start          	|  2.3538e-05     	|7              	|  0.00016476     	|  5.1676e-05     	|
on_fit_start                       	|  6.3337e-05     	|1              	|  6.3337e-05     	|  1.9865e-05     	|
on_train_dataloader                	|  3.6638e-05     	|1              	|  3.6638e-05     	|  1.1491e-05     	|
on_val_dataloader                  	|  2.3423e-05     	|1              	|  2.3423e-05     	|  7.3465e-06     	|
on_before_accelerator_backend_setup	|  1.018e-05      	|1              	|  1.018e-05      	|  3.193e-06      	|

[2022-01-18 16:10:32,725 INFO @src.logger.base_logger] 19 - Running script at src.train
[2022-01-18 16:10:33,654 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:10:33,664 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:10:33,978 DEBUG @src.logger.base_logger] 23 - Detected device: cuda
[2022-01-18 16:10:33,979 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:10:33,979 INFO @src.logger.base_logger] 51 - CuDNN is enabled: True
[2022-01-18 16:10:34,084 INFO @pytorch_lightning.utilities.distributed] 1294 - GPU available: True, used: True
[2022-01-18 16:10:34,084 INFO @pytorch_lightning.utilities.distributed] 1297 - TPU available: False, using: 0 TPU cores
[2022-01-18 16:10:34,084 INFO @pytorch_lightning.utilities.distributed] 1300 - IPU available: False, using: 0 IPUs
[2022-01-18 16:10:34,085 INFO @src.logger.base_logger] 153 - Precision: 32
[2022-01-18 16:10:34,085 INFO @src.logger.base_logger] 154 - Train the mobilenetv3 model.
[2022-01-18 16:10:34,148 INFO @src.logger.base_logger] 19 - Running script at src.train
[2022-01-18 16:10:35,101 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:10:35,115 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:10:35,457 DEBUG @src.logger.base_logger] 23 - Detected device: cuda
[2022-01-18 16:10:35,458 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:10:35,458 INFO @src.logger.base_logger] 51 - CuDNN is enabled: True
[2022-01-18 16:10:35,562 INFO @src.logger.base_logger] 153 - Precision: 32
[2022-01-18 16:10:35,562 INFO @src.logger.base_logger] 154 - Train the mobilenetv3 model.
[2022-01-18 16:10:35,562 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:10:35,564 INFO @pytorch_lightning.plugins.training_type.ddp] 322 - initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
[2022-01-18 16:10:35,865 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:10:35,868 INFO @pytorch_lightning.plugins.training_type.ddp] 322 - initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
[2022-01-18 16:10:36,565 INFO @torch.distributed.distributed_c10d] 196 - Added key: store_based_barrier_key:1 to store for rank: 1
[2022-01-18 16:10:36,568 INFO @torch.distributed.distributed_c10d] 196 - Added key: store_based_barrier_key:1 to store for rank: 0
[2022-01-18 16:10:36,568 INFO @torch.distributed.distributed_c10d] 226 - Rank 0: Completed store-based barrier for 2 nodes.
[2022-01-18 16:10:36,568 INFO @pytorch_lightning.utilities.distributed] 328 - ----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All DDP processes registered. Starting ddp with 2 processes
----------------------------------------------------------------------------------------------------

[2022-01-18 16:10:36,576 INFO @torch.distributed.distributed_c10d] 226 - Rank 1: Completed store-based barrier for 2 nodes.
[2022-01-18 16:10:40,426 INFO @pytorch_lightning.accelerators.gpu] 54 - LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
[2022-01-18 16:10:40,427 INFO @pytorch_lightning.accelerators.gpu] 54 - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
[2022-01-18 16:10:40,525 DEBUG @git.cmd] 869 - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:10:40,683 DEBUG @urllib3.connectionpool] 227 - Starting new HTTP connection (1): localhost:8080
[2022-01-18 16:10:40,690 DEBUG @urllib3.connectionpool] 452 - http://localhost:8080 "POST /graphql HTTP/1.1" 200 464
[2022-01-18 16:10:40,695 DEBUG @urllib3.connectionpool] 227 - Starting new HTTP connection (1): localhost:8080
[2022-01-18 16:10:40,701 DEBUG @urllib3.connectionpool] 452 - http://localhost:8080 "POST /graphql HTTP/1.1" 200 368
[2022-01-18 16:10:43,821 INFO @pytorch_lightning.core.lightning] 1736 - 
  | Name          | Type             | Params
---------------------------------------------------
0 | net           | MobileNetV3      | 4.3 M 
1 | criterion     | CrossEntropyLoss | 0     
2 | train_metrics | MetricCollection | 0     
3 | val_metrics   | MetricCollection | 0     
4 | test_metrics  | MetricCollection | 0     
---------------------------------------------------
4.3 M     Trainable params
0         Non-trainable params
4.3 M     Total params
17.141    Total estimated model params size (MB)
[2022-01-18 16:10:46,769 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:10:46,770 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:11:41,135 INFO @pytorch_lightning.callbacks.early_stopping] 267 - [rank: 0] Metric train_Accuracy improved. New best score: 0.167
[2022-01-18 16:11:41,135 INFO @pytorch_lightning.callbacks.early_stopping] 267 - [rank: 1] Metric train_Accuracy improved. New best score: 0.062
[2022-01-18 16:12:36,325 INFO @pytorch_lightning.callbacks.early_stopping] 267 - [rank: 1] Metric train_Accuracy improved by 0.042 >= min_delta = 0.001. New best score: 0.104
[2022-01-18 16:13:31,171 INFO @pytorch_lightning.callbacks.early_stopping] 267 - [rank: 1] Metric train_Accuracy improved by 0.021 >= min_delta = 0.001. New best score: 0.125
[2022-01-18 16:16:16,052 INFO @pytorch_lightning.callbacks.early_stopping] 267 - [rank: 0] Monitored metric train_Accuracy did not improve in the last 5 records. Best score: 0.167. Signaling Trainer to stop.
[2022-01-18 16:17:10,797 INFO @pytorch_lightning.callbacks.early_stopping] 267 - [rank: 0] Monitored metric train_Accuracy did not improve in the last 6 records. Best score: 0.167. Signaling Trainer to stop.
[2022-01-18 16:18:05,520 INFO @pytorch_lightning.callbacks.early_stopping] 267 - [rank: 1] Monitored metric train_Accuracy did not improve in the last 5 records. Best score: 0.125. Signaling Trainer to stop.
[2022-01-18 16:18:05,520 INFO @pytorch_lightning.callbacks.early_stopping] 267 - [rank: 0] Monitored metric train_Accuracy did not improve in the last 7 records. Best score: 0.167. Signaling Trainer to stop.
[2022-01-18 16:18:05,702 DEBUG @urllib3.connectionpool] 227 - Starting new HTTP connection (1): localhost:8080
[2022-01-18 16:18:05,709 DEBUG @urllib3.connectionpool] 452 - http://localhost:8080 "POST /graphql HTTP/1.1" 200 58
[2022-01-18 16:18:05,720 INFO @pytorch_lightning.profiler.base] 113 - FIT Profiler Report

Action                             	|  Mean duration (s)	|Num calls      	|  Total time (s) 	|  Percentage %   	|
--------------------------------------------------------------------------------------------------------------------------------------
Total                              	|  -              	|_              	|  451.63         	|  100 %          	|
--------------------------------------------------------------------------------------------------------------------------------------
run_training_epoch                 	|  54.832         	|8              	|  438.65         	|  97.127         	|
run_training_batch                 	|  0.37411        	|944            	|  353.16         	|  78.197         	|
model_forward                      	|  0.36791        	|944            	|  347.31         	|  76.901         	|
training_step                      	|  0.36781        	|944            	|  347.21         	|  76.879         	|
closure_0                          	|  0.24817        	|944            	|  234.28         	|  51.874         	|
get_train_batch                    	|  0.03394        	|944            	|  32.039         	|  7.0941         	|
evaluation_step_and_end            	|  0.09728        	|162            	|  15.759         	|  3.4894         	|
validation_step                    	|  0.097179       	|162            	|  15.743         	|  3.4858         	|
training_batch_to_device           	|  0.0128         	|944            	|  12.083         	|  2.6755         	|
evaluation_batch_to_device         	|  0.012691       	|162            	|  2.056          	|  0.45523        	|
on_train_batch_end                 	|  0.00022625     	|944            	|  0.21358        	|  0.047292       	|
on_train_epoch_end                 	|  0.025023       	|8              	|  0.20019        	|  0.044326       	|
on_after_backward                  	|  8.0592e-05     	|944            	|  0.076079       	|  0.016846       	|
on_before_optimizer_step           	|  5.8102e-05     	|944            	|  0.054849       	|  0.012145       	|
on_validation_batch_end            	|  0.0002485      	|162            	|  0.040257       	|  0.0089136      	|
on_before_backward                 	|  3.5555e-05     	|944            	|  0.033564       	|  0.0074317      	|
on_batch_start                     	|  3.2579e-05     	|944            	|  0.030754       	|  0.0068096      	|
on_train_batch_start               	|  2.9692e-05     	|944            	|  0.028029       	|  0.0062062      	|
on_batch_end                       	|  2.3483e-05     	|944            	|  0.022168       	|  0.0049085      	|
training_step_end                  	|  1.8412e-05     	|944            	|  0.017381       	|  0.0038484      	|
on_validation_end                  	|  0.0018176      	|9              	|  0.016359       	|  0.0036222      	|
on_train_epoch_start               	|  0.0020343      	|8              	|  0.016274       	|  0.0036034      	|
on_train_start                     	|  0.0085135      	|1              	|  0.0085135      	|  0.0018851      	|
on_validation_batch_start          	|  4.0931e-05     	|162            	|  0.0066309      	|  0.0014682      	|
on_validation_start                	|  0.00063056     	|9              	|  0.005675       	|  0.0012566      	|
validation_step_end                	|  2.0896e-05     	|162            	|  0.0033851      	|  0.00074953     	|
on_epoch_end                       	|  3.9956e-05     	|17             	|  0.00067925     	|  0.0001504      	|
on_epoch_start                     	|  3.339e-05      	|17             	|  0.00056763     	|  0.00012568     	|
on_validation_epoch_end            	|  5.7464e-05     	|9              	|  0.00051718     	|  0.00011451     	|
on_train_end                       	|  0.00046079     	|1              	|  0.00046079     	|  0.00010203     	|
on_validation_epoch_start          	|  2.4213e-05     	|9              	|  0.00021792     	|  4.8251e-05     	|
on_fit_start                       	|  5.9832e-05     	|1              	|  5.9832e-05     	|  1.3248e-05     	|
on_train_dataloader                	|  4.7906e-05     	|1              	|  4.7906e-05     	|  1.0607e-05     	|
on_val_dataloader                  	|  2.7606e-05     	|1              	|  2.7606e-05     	|  6.1125e-06     	|
on_before_accelerator_backend_setup	|  9.8543e-06     	|1              	|  9.8543e-06     	|  2.182e-06      	|

[2022-01-18 16:27:49,138 INFO @src.logger.base_logger] 19 - Running script at src.train
[2022-01-18 16:27:50,098 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:27:50,108 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:27:50,405 DEBUG @src.logger.base_logger] 23 - Detected device: cuda
[2022-01-18 16:27:50,406 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:27:50,406 INFO @src.logger.base_logger] 51 - CuDNN is enabled: True
[2022-01-18 16:27:51,346 INFO @pytorch_lightning.utilities.distributed] 1294 - GPU available: True, used: True
[2022-01-18 16:27:51,346 INFO @pytorch_lightning.utilities.distributed] 1297 - TPU available: False, using: 0 TPU cores
[2022-01-18 16:27:51,346 INFO @pytorch_lightning.utilities.distributed] 1300 - IPU available: False, using: 0 IPUs
[2022-01-18 16:27:51,346 INFO @src.logger.base_logger] 157 - Precision: 32
[2022-01-18 16:27:51,346 INFO @src.logger.base_logger] 158 - Train the mobilenetv3 model.
[2022-01-18 16:27:51,414 INFO @src.logger.base_logger] 19 - Running script at src.train
[2022-01-18 16:27:52,538 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:27:52,549 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:27:52,908 DEBUG @src.logger.base_logger] 23 - Detected device: cuda
[2022-01-18 16:27:52,909 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:27:52,909 INFO @src.logger.base_logger] 51 - CuDNN is enabled: True
[2022-01-18 16:27:53,133 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:27:53,136 INFO @pytorch_lightning.plugins.training_type.ddp] 322 - initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
[2022-01-18 16:27:53,929 INFO @src.logger.base_logger] 157 - Precision: 32
[2022-01-18 16:27:53,929 INFO @src.logger.base_logger] 158 - Train the mobilenetv3 model.
[2022-01-18 16:27:53,930 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:27:53,931 INFO @pytorch_lightning.plugins.training_type.ddp] 322 - initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
[2022-01-18 16:27:53,932 INFO @torch.distributed.distributed_c10d] 196 - Added key: store_based_barrier_key:1 to store for rank: 1
[2022-01-18 16:27:53,942 INFO @torch.distributed.distributed_c10d] 196 - Added key: store_based_barrier_key:1 to store for rank: 0
[2022-01-18 16:27:53,943 INFO @torch.distributed.distributed_c10d] 226 - Rank 1: Completed store-based barrier for 2 nodes.
[2022-01-18 16:27:53,943 INFO @torch.distributed.distributed_c10d] 226 - Rank 0: Completed store-based barrier for 2 nodes.
[2022-01-18 16:27:53,943 INFO @pytorch_lightning.utilities.distributed] 328 - ----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All DDP processes registered. Starting ddp with 2 processes
----------------------------------------------------------------------------------------------------

[2022-01-18 16:27:58,168 INFO @pytorch_lightning.accelerators.gpu] 54 - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
[2022-01-18 16:27:58,170 INFO @pytorch_lightning.accelerators.gpu] 54 - LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
[2022-01-18 16:27:58,254 DEBUG @git.cmd] 869 - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:27:58,422 DEBUG @urllib3.connectionpool] 227 - Starting new HTTP connection (1): localhost:8080
[2022-01-18 16:27:58,435 DEBUG @urllib3.connectionpool] 452 - http://localhost:8080 "POST /graphql HTTP/1.1" 200 464
[2022-01-18 16:27:58,443 DEBUG @urllib3.connectionpool] 227 - Starting new HTTP connection (1): localhost:8080
[2022-01-18 16:27:58,449 DEBUG @urllib3.connectionpool] 452 - http://localhost:8080 "POST /graphql HTTP/1.1" 200 368
[2022-01-18 16:28:01,911 INFO @pytorch_lightning.core.lightning] 1736 - 
  | Name          | Type             | Params
---------------------------------------------------
0 | net           | MobileNetV3      | 4.3 M 
1 | criterion     | CrossEntropyLoss | 0     
2 | train_metrics | MetricCollection | 0     
3 | val_metrics   | MetricCollection | 0     
4 | test_metrics  | MetricCollection | 0     
---------------------------------------------------
4.3 M     Trainable params
0         Non-trainable params
4.3 M     Total params
17.142    Total estimated model params size (MB)
[2022-01-18 16:28:07,624 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:28:07,627 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:28:18,090 ERROR @src.logger.base_logger] 25 - The script halted with an error
Traceback (most recent call last):
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/main.py", line 22, in run
    mod.run(args)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/train.py", line 162, in run
    trainer.fit(model, train_loader, valid_loader)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 922, in _run
    self._dispatch()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _dispatch
    self.accelerator.start_training(self)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1000, in run_stage
    return self._run_train()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1049, in _run_train
    self.fit_loop.run()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 130, in advance
    batch_output = self.batch_loop.run(batch, self.iteration_count, self._dataloader_idx)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 100, in run
    super().run(batch, batch_idx, dataloader_idx)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 152, in advance
    result = self._run_optimization(batch_idx, split_batch)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 203, in _run_optimization
    result = self._training_step(split_batch, batch_idx, opt_idx, self._hiddens)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 306, in _training_step
    training_step_output = self.trainer.accelerator.training_step(step_kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 193, in training_step
    return self.training_type_plugin.training_step(*step_kwargs.values())
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 389, in training_step
    return self.model(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 82, in forward
    output = self.module.training_step(*inputs, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 257, in training_step
    logits = self(x)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 251, in forward
    return self.net(x)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 179, in forward
    out = self.net_blocks(x)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 133, in forward
    out = self.non_lin(out)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 62, in forward
    return x * self.hsigmoid(x)
RuntimeError: CUDA out of memory. Tried to allocate 184.00 MiB (GPU 1; 23.65 GiB total capacity; 21.80 GiB already allocated; 49.00 MiB free; 21.89 GiB reserved in total by PyTorch)
[2022-01-18 16:28:19,174 ERROR @src.logger.base_logger] 25 - The script halted with an error
Traceback (most recent call last):
  File "main.py", line 22, in run
    mod.run(args)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/train.py", line 162, in run
    trainer.fit(model, train_loader, valid_loader)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 922, in _run
    self._dispatch()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _dispatch
    self.accelerator.start_training(self)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1000, in run_stage
    return self._run_train()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1049, in _run_train
    self.fit_loop.run()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 130, in advance
    batch_output = self.batch_loop.run(batch, self.iteration_count, self._dataloader_idx)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 100, in run
    super().run(batch, batch_idx, dataloader_idx)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 152, in advance
    result = self._run_optimization(batch_idx, split_batch)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 203, in _run_optimization
    result = self._training_step(split_batch, batch_idx, opt_idx, self._hiddens)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 306, in _training_step
    training_step_output = self.trainer.accelerator.training_step(step_kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 193, in training_step
    return self.training_type_plugin.training_step(*step_kwargs.values())
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 389, in training_step
    return self.model(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 82, in forward
    output = self.module.training_step(*inputs, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 257, in training_step
    logits = self(x)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 251, in forward
    return self.net(x)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 179, in forward
    out = self.net_blocks(x)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 127, in forward
    out = self.non_lin(out)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 62, in forward
    return x * self.hsigmoid(x)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 54, in forward
    return F.relu6(x + 3, inplace=self.inplace) / 6
RuntimeError: CUDA out of memory. Tried to allocate 78.00 MiB (GPU 0; 23.65 GiB total capacity; 17.70 GiB already allocated; 11.94 MiB free; 17.74 GiB reserved in total by PyTorch)
[2022-01-18 16:29:29,728 INFO @src.logger.base_logger] 19 - Running script at src.train
[2022-01-18 16:29:30,687 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:29:30,700 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:29:31,007 DEBUG @src.logger.base_logger] 23 - Detected device: cuda
[2022-01-18 16:29:31,008 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:29:31,008 INFO @src.logger.base_logger] 51 - CuDNN is enabled: True
[2022-01-18 16:29:31,961 INFO @pytorch_lightning.utilities.distributed] 1294 - GPU available: True, used: True
[2022-01-18 16:29:31,961 INFO @pytorch_lightning.utilities.distributed] 1297 - TPU available: False, using: 0 TPU cores
[2022-01-18 16:29:31,961 INFO @pytorch_lightning.utilities.distributed] 1300 - IPU available: False, using: 0 IPUs
[2022-01-18 16:29:31,961 INFO @src.logger.base_logger] 157 - Precision: 32
[2022-01-18 16:29:31,961 INFO @src.logger.base_logger] 158 - Train the mobilenetv3 model.
[2022-01-18 16:29:32,032 INFO @src.logger.base_logger] 19 - Running script at src.train
[2022-01-18 16:29:33,008 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:29:33,018 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:29:33,317 DEBUG @src.logger.base_logger] 23 - Detected device: cuda
[2022-01-18 16:29:33,318 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:29:33,319 INFO @src.logger.base_logger] 51 - CuDNN is enabled: True
[2022-01-18 16:29:33,749 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:29:33,752 INFO @pytorch_lightning.plugins.training_type.ddp] 322 - initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
[2022-01-18 16:29:34,373 INFO @src.logger.base_logger] 157 - Precision: 32
[2022-01-18 16:29:34,373 INFO @src.logger.base_logger] 158 - Train the mobilenetv3 model.
[2022-01-18 16:29:34,374 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:29:34,376 INFO @pytorch_lightning.plugins.training_type.ddp] 322 - initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
[2022-01-18 16:29:34,376 INFO @torch.distributed.distributed_c10d] 196 - Added key: store_based_barrier_key:1 to store for rank: 1
[2022-01-18 16:29:34,379 INFO @torch.distributed.distributed_c10d] 196 - Added key: store_based_barrier_key:1 to store for rank: 0
[2022-01-18 16:29:34,379 INFO @torch.distributed.distributed_c10d] 226 - Rank 0: Completed store-based barrier for 2 nodes.
[2022-01-18 16:29:34,380 INFO @pytorch_lightning.utilities.distributed] 328 - ----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All DDP processes registered. Starting ddp with 2 processes
----------------------------------------------------------------------------------------------------

[2022-01-18 16:29:34,387 INFO @torch.distributed.distributed_c10d] 226 - Rank 1: Completed store-based barrier for 2 nodes.
[2022-01-18 16:29:38,548 INFO @pytorch_lightning.accelerators.gpu] 54 - LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
[2022-01-18 16:29:38,549 INFO @pytorch_lightning.accelerators.gpu] 54 - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
[2022-01-18 16:29:38,658 DEBUG @git.cmd] 869 - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:29:38,813 DEBUG @urllib3.connectionpool] 227 - Starting new HTTP connection (1): localhost:8080
[2022-01-18 16:29:38,820 DEBUG @urllib3.connectionpool] 452 - http://localhost:8080 "POST /graphql HTTP/1.1" 200 464
[2022-01-18 16:29:38,828 DEBUG @urllib3.connectionpool] 227 - Starting new HTTP connection (1): localhost:8080
[2022-01-18 16:29:38,834 DEBUG @urllib3.connectionpool] 452 - http://localhost:8080 "POST /graphql HTTP/1.1" 200 368
[2022-01-18 16:29:41,990 INFO @pytorch_lightning.core.lightning] 1736 - 
  | Name          | Type             | Params
---------------------------------------------------
0 | net           | MobileNetV3      | 4.3 M 
1 | criterion     | CrossEntropyLoss | 0     
2 | train_metrics | MetricCollection | 0     
3 | val_metrics   | MetricCollection | 0     
4 | test_metrics  | MetricCollection | 0     
---------------------------------------------------
4.3 M     Trainable params
0         Non-trainable params
4.3 M     Total params
17.142    Total estimated model params size (MB)
[2022-01-18 16:29:48,493 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:29:48,495 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:30:01,468 ERROR @src.logger.base_logger] 25 - The script halted with an error
Traceback (most recent call last):
  File "main.py", line 22, in run
    mod.run(args)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/train.py", line 162, in run
    trainer.fit(model, train_loader, valid_loader)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 922, in _run
    self._dispatch()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _dispatch
    self.accelerator.start_training(self)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1000, in run_stage
    return self._run_train()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1049, in _run_train
    self.fit_loop.run()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 130, in advance
    batch_output = self.batch_loop.run(batch, self.iteration_count, self._dataloader_idx)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 100, in run
    super().run(batch, batch_idx, dataloader_idx)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 152, in advance
    result = self._run_optimization(batch_idx, split_batch)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 203, in _run_optimization
    result = self._training_step(split_batch, batch_idx, opt_idx, self._hiddens)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 306, in _training_step
    training_step_output = self.trainer.accelerator.training_step(step_kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 193, in training_step
    return self.training_type_plugin.training_step(*step_kwargs.values())
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 389, in training_step
    return self.model(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 82, in forward
    output = self.module.training_step(*inputs, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 257, in training_step
    logits = self(x)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 251, in forward
    return self.net(x)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 179, in forward
    out = self.net_blocks(x)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 127, in forward
    out = self.non_lin(out)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 62, in forward
    return x * self.hsigmoid(x)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 54, in forward
    return F.relu6(x + 3, inplace=self.inplace) / 6
RuntimeError: CUDA out of memory. Tried to allocate 78.00 MiB (GPU 0; 23.65 GiB total capacity; 17.70 GiB already allocated; 3.94 MiB free; 17.74 GiB reserved in total by PyTorch)
[2022-01-18 16:30:02,604 ERROR @src.logger.base_logger] 25 - The script halted with an error
Traceback (most recent call last):
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/main.py", line 22, in run
    mod.run(args)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/train.py", line 162, in run
    trainer.fit(model, train_loader, valid_loader)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 922, in _run
    self._dispatch()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _dispatch
    self.accelerator.start_training(self)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1000, in run_stage
    return self._run_train()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1049, in _run_train
    self.fit_loop.run()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 130, in advance
    batch_output = self.batch_loop.run(batch, self.iteration_count, self._dataloader_idx)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 100, in run
    super().run(batch, batch_idx, dataloader_idx)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 152, in advance
    result = self._run_optimization(batch_idx, split_batch)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 203, in _run_optimization
    result = self._training_step(split_batch, batch_idx, opt_idx, self._hiddens)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 306, in _training_step
    training_step_output = self.trainer.accelerator.training_step(step_kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 193, in training_step
    return self.training_type_plugin.training_step(*step_kwargs.values())
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 389, in training_step
    return self.model(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 82, in forward
    output = self.module.training_step(*inputs, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 257, in training_step
    logits = self(x)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 251, in forward
    return self.net(x)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 179, in forward
    out = self.net_blocks(x)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 133, in forward
    out = self.non_lin(out)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 62, in forward
    return x * self.hsigmoid(x)
RuntimeError: CUDA out of memory. Tried to allocate 184.00 MiB (GPU 1; 23.65 GiB total capacity; 21.80 GiB already allocated; 40.81 MiB free; 21.89 GiB reserved in total by PyTorch)
[2022-01-18 16:31:18,832 INFO @src.logger.base_logger] 19 - Running script at src.train
[2022-01-18 16:31:19,778 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:31:19,788 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:31:20,118 DEBUG @src.logger.base_logger] 23 - Detected device: cuda
[2022-01-18 16:31:20,119 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:31:20,119 INFO @src.logger.base_logger] 51 - CuDNN is enabled: True
[2022-01-18 16:31:21,064 INFO @pytorch_lightning.utilities.distributed] 1294 - GPU available: True, used: True
[2022-01-18 16:31:21,064 INFO @pytorch_lightning.utilities.distributed] 1297 - TPU available: False, using: 0 TPU cores
[2022-01-18 16:31:21,064 INFO @pytorch_lightning.utilities.distributed] 1300 - IPU available: False, using: 0 IPUs
[2022-01-18 16:31:21,065 INFO @src.logger.base_logger] 157 - Precision: 32
[2022-01-18 16:31:21,065 INFO @src.logger.base_logger] 158 - Train the mobilenetv3 model.
[2022-01-18 16:31:21,129 INFO @src.logger.base_logger] 19 - Running script at src.train
[2022-01-18 16:31:22,092 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:31:22,103 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:31:22,399 DEBUG @src.logger.base_logger] 23 - Detected device: cuda
[2022-01-18 16:31:22,400 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:31:22,400 INFO @src.logger.base_logger] 51 - CuDNN is enabled: True
[2022-01-18 16:31:22,851 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:31:22,854 INFO @pytorch_lightning.plugins.training_type.ddp] 322 - initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
[2022-01-18 16:31:23,374 INFO @src.logger.base_logger] 157 - Precision: 32
[2022-01-18 16:31:23,374 INFO @src.logger.base_logger] 158 - Train the mobilenetv3 model.
[2022-01-18 16:31:23,374 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:31:23,376 INFO @pytorch_lightning.plugins.training_type.ddp] 322 - initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
[2022-01-18 16:31:23,376 INFO @torch.distributed.distributed_c10d] 196 - Added key: store_based_barrier_key:1 to store for rank: 1
[2022-01-18 16:31:23,379 INFO @torch.distributed.distributed_c10d] 196 - Added key: store_based_barrier_key:1 to store for rank: 0
[2022-01-18 16:31:23,379 INFO @torch.distributed.distributed_c10d] 226 - Rank 0: Completed store-based barrier for 2 nodes.
[2022-01-18 16:31:23,380 INFO @pytorch_lightning.utilities.distributed] 328 - ----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All DDP processes registered. Starting ddp with 2 processes
----------------------------------------------------------------------------------------------------

[2022-01-18 16:31:23,391 INFO @torch.distributed.distributed_c10d] 226 - Rank 1: Completed store-based barrier for 2 nodes.
[2022-01-18 16:31:27,247 INFO @pytorch_lightning.accelerators.gpu] 54 - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
[2022-01-18 16:31:27,247 INFO @pytorch_lightning.accelerators.gpu] 54 - LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
[2022-01-18 16:31:27,332 DEBUG @git.cmd] 869 - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:31:27,475 DEBUG @urllib3.connectionpool] 227 - Starting new HTTP connection (1): localhost:8080
[2022-01-18 16:31:27,481 DEBUG @urllib3.connectionpool] 452 - http://localhost:8080 "POST /graphql HTTP/1.1" 200 464
[2022-01-18 16:31:27,486 DEBUG @urllib3.connectionpool] 227 - Starting new HTTP connection (1): localhost:8080
[2022-01-18 16:31:27,492 DEBUG @urllib3.connectionpool] 452 - http://localhost:8080 "POST /graphql HTTP/1.1" 200 368
[2022-01-18 16:31:30,615 INFO @pytorch_lightning.core.lightning] 1736 - 
  | Name          | Type             | Params
---------------------------------------------------
0 | net           | MobileNetV3      | 4.3 M 
1 | criterion     | CrossEntropyLoss | 0     
2 | train_metrics | MetricCollection | 0     
3 | val_metrics   | MetricCollection | 0     
4 | test_metrics  | MetricCollection | 0     
---------------------------------------------------
4.3 M     Trainable params
0         Non-trainable params
4.3 M     Total params
17.142    Total estimated model params size (MB)
[2022-01-18 16:31:36,555 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:31:36,558 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:31:47,803 ERROR @src.logger.base_logger] 25 - The script halted with an error
Traceback (most recent call last):
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/main.py", line 22, in run
    mod.run(args)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/train.py", line 162, in run
    trainer.fit(model, train_loader, valid_loader)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 922, in _run
    self._dispatch()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _dispatch
    self.accelerator.start_training(self)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1000, in run_stage
    return self._run_train()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1049, in _run_train
    self.fit_loop.run()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 130, in advance
    batch_output = self.batch_loop.run(batch, self.iteration_count, self._dataloader_idx)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 100, in run
    super().run(batch, batch_idx, dataloader_idx)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 152, in advance
    result = self._run_optimization(batch_idx, split_batch)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 203, in _run_optimization
    result = self._training_step(split_batch, batch_idx, opt_idx, self._hiddens)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 306, in _training_step
    training_step_output = self.trainer.accelerator.training_step(step_kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 193, in training_step
    return self.training_type_plugin.training_step(*step_kwargs.values())
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 389, in training_step
    return self.model(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 82, in forward
    output = self.module.training_step(*inputs, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 257, in training_step
    logits = self(x)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 251, in forward
    return self.net(x)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 179, in forward
    out = self.net_blocks(x)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 133, in forward
    out = self.non_lin(out)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 62, in forward
    return x * self.hsigmoid(x)
RuntimeError: CUDA out of memory. Tried to allocate 184.00 MiB (GPU 1; 23.65 GiB total capacity; 21.80 GiB already allocated; 46.44 MiB free; 21.89 GiB reserved in total by PyTorch)
[2022-01-18 16:31:50,654 ERROR @src.logger.base_logger] 25 - The script halted with an error
Traceback (most recent call last):
  File "main.py", line 22, in run
    mod.run(args)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/train.py", line 162, in run
    trainer.fit(model, train_loader, valid_loader)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 922, in _run
    self._dispatch()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _dispatch
    self.accelerator.start_training(self)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1000, in run_stage
    return self._run_train()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1049, in _run_train
    self.fit_loop.run()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 130, in advance
    batch_output = self.batch_loop.run(batch, self.iteration_count, self._dataloader_idx)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 100, in run
    super().run(batch, batch_idx, dataloader_idx)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 152, in advance
    result = self._run_optimization(batch_idx, split_batch)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 203, in _run_optimization
    result = self._training_step(split_batch, batch_idx, opt_idx, self._hiddens)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 306, in _training_step
    training_step_output = self.trainer.accelerator.training_step(step_kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 193, in training_step
    return self.training_type_plugin.training_step(*step_kwargs.values())
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 389, in training_step
    return self.model(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 82, in forward
    output = self.module.training_step(*inputs, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 257, in training_step
    logits = self(x)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 251, in forward
    return self.net(x)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 179, in forward
    out = self.net_blocks(x)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 127, in forward
    out = self.non_lin(out)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 62, in forward
    return x * self.hsigmoid(x)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 54, in forward
    return F.relu6(x + 3, inplace=self.inplace) / 6
RuntimeError: CUDA out of memory. Tried to allocate 78.00 MiB (GPU 0; 23.65 GiB total capacity; 17.63 GiB already allocated; 79.94 MiB free; 17.66 GiB reserved in total by PyTorch)
[2022-01-18 16:32:51,320 INFO @src.logger.base_logger] 19 - Running script at src.train
[2022-01-18 16:32:52,267 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:32:52,277 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:32:52,567 DEBUG @src.logger.base_logger] 23 - Detected device: cuda
[2022-01-18 16:32:52,568 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:32:52,569 INFO @src.logger.base_logger] 51 - CuDNN is enabled: True
[2022-01-18 16:32:53,503 INFO @pytorch_lightning.utilities.distributed] 1294 - GPU available: True, used: True
[2022-01-18 16:32:53,503 INFO @pytorch_lightning.utilities.distributed] 1297 - TPU available: False, using: 0 TPU cores
[2022-01-18 16:32:53,503 INFO @pytorch_lightning.utilities.distributed] 1300 - IPU available: False, using: 0 IPUs
[2022-01-18 16:32:53,503 INFO @src.logger.base_logger] 157 - Precision: 32
[2022-01-18 16:32:53,503 INFO @src.logger.base_logger] 158 - Train the mobilenetv3 model.
[2022-01-18 16:32:53,568 INFO @src.logger.base_logger] 19 - Running script at src.train
[2022-01-18 16:32:54,534 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:32:54,545 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:32:54,841 DEBUG @src.logger.base_logger] 23 - Detected device: cuda
[2022-01-18 16:32:54,842 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:32:54,842 INFO @src.logger.base_logger] 51 - CuDNN is enabled: True
[2022-01-18 16:32:55,292 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:32:55,294 INFO @pytorch_lightning.plugins.training_type.ddp] 322 - initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
[2022-01-18 16:32:55,826 INFO @src.logger.base_logger] 157 - Precision: 32
[2022-01-18 16:32:55,826 INFO @src.logger.base_logger] 158 - Train the mobilenetv3 model.
[2022-01-18 16:32:55,827 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:32:55,828 INFO @pytorch_lightning.plugins.training_type.ddp] 322 - initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
[2022-01-18 16:32:55,829 INFO @torch.distributed.distributed_c10d] 196 - Added key: store_based_barrier_key:1 to store for rank: 1
[2022-01-18 16:32:55,830 INFO @torch.distributed.distributed_c10d] 196 - Added key: store_based_barrier_key:1 to store for rank: 0
[2022-01-18 16:32:55,830 INFO @torch.distributed.distributed_c10d] 226 - Rank 0: Completed store-based barrier for 2 nodes.
[2022-01-18 16:32:55,830 INFO @pytorch_lightning.utilities.distributed] 328 - ----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All DDP processes registered. Starting ddp with 2 processes
----------------------------------------------------------------------------------------------------

[2022-01-18 16:32:55,839 INFO @torch.distributed.distributed_c10d] 226 - Rank 1: Completed store-based barrier for 2 nodes.
[2022-01-18 16:32:59,666 INFO @pytorch_lightning.accelerators.gpu] 54 - LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
[2022-01-18 16:32:59,666 INFO @pytorch_lightning.accelerators.gpu] 54 - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
[2022-01-18 16:32:59,754 DEBUG @git.cmd] 869 - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:32:59,896 DEBUG @urllib3.connectionpool] 227 - Starting new HTTP connection (1): localhost:8080
[2022-01-18 16:32:59,902 DEBUG @urllib3.connectionpool] 452 - http://localhost:8080 "POST /graphql HTTP/1.1" 200 464
[2022-01-18 16:32:59,907 DEBUG @urllib3.connectionpool] 227 - Starting new HTTP connection (1): localhost:8080
[2022-01-18 16:32:59,912 DEBUG @urllib3.connectionpool] 452 - http://localhost:8080 "POST /graphql HTTP/1.1" 200 368
[2022-01-18 16:33:02,942 INFO @pytorch_lightning.core.lightning] 1736 - 
  | Name          | Type             | Params
---------------------------------------------------
0 | net           | MobileNetV3      | 4.3 M 
1 | criterion     | CrossEntropyLoss | 0     
2 | train_metrics | MetricCollection | 0     
3 | val_metrics   | MetricCollection | 0     
4 | test_metrics  | MetricCollection | 0     
---------------------------------------------------
4.3 M     Trainable params
0         Non-trainable params
4.3 M     Total params
17.142    Total estimated model params size (MB)
[2022-01-18 16:33:08,262 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:33:08,262 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:39:55,523 ERROR @src.logger.base_logger] 25 - The script halted with an error
Traceback (most recent call last):
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/queue.py", line 178, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1049, in _run_train
    self.fit_loop.run()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 112, in run
    self.on_advance_end()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 177, in on_advance_end
    self._run_validation()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 257, in _run_validation
    self.val_loop.run()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 94, in advance
    batch_idx, batch = next(dataloader_iter)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1142, in _get_data
    success, data = self._try_get_data()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1003, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 5201, 5203, 5205, 5207, 5208, 5210, 5212, 5214, 5216, 5218, 5220, 5222, 5223, 5225, 5227, 5229, 5234, 5236, 5238, 5240, 5242, 5244, 5246, 5248, 5250) exited unexpectedly

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/main.py", line 22, in run
    mod.run(args)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/train.py", line 162, in run
    trainer.fit(model, train_loader, valid_loader)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 922, in _run
    self._dispatch()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _dispatch
    self.accelerator.start_training(self)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1000, in run_stage
    return self._run_train()
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1062, in _run_train
    self.training_type_plugin.reconciliate_processes(traceback.format_exc())
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 476, in reconciliate_processes
    os.kill(pid, signal.SIGKILL)
ProcessLookupError: [Errno 3] No such process
[2022-01-18 16:40:14,367 INFO @src.logger.base_logger] 19 - Running script at src.train
[2022-01-18 16:40:15,265 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:40:15,278 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:40:15,594 DEBUG @src.logger.base_logger] 23 - Detected device: cuda
[2022-01-18 16:40:15,595 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:40:15,595 INFO @src.logger.base_logger] 51 - CuDNN is enabled: True
[2022-01-18 16:40:15,687 INFO @pytorch_lightning.utilities.distributed] 1294 - GPU available: True, used: True
[2022-01-18 16:40:15,687 INFO @pytorch_lightning.utilities.distributed] 1297 - TPU available: False, using: 0 TPU cores
[2022-01-18 16:40:15,687 INFO @pytorch_lightning.utilities.distributed] 1300 - IPU available: False, using: 0 IPUs
[2022-01-18 16:40:15,687 INFO @src.logger.base_logger] 157 - Precision: 32
[2022-01-18 16:40:15,687 INFO @src.logger.base_logger] 158 - Train the mobilenetv3 model.
[2022-01-18 16:40:15,748 INFO @src.logger.base_logger] 19 - Running script at src.train
[2022-01-18 16:40:16,770 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:40:16,785 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:40:17,121 DEBUG @src.logger.base_logger] 23 - Detected device: cuda
[2022-01-18 16:40:17,122 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:40:17,123 INFO @src.logger.base_logger] 51 - CuDNN is enabled: True
[2022-01-18 16:40:17,211 INFO @src.logger.base_logger] 157 - Precision: 32
[2022-01-18 16:40:17,212 INFO @src.logger.base_logger] 158 - Train the mobilenetv3 model.
[2022-01-18 16:40:17,212 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:40:17,213 INFO @pytorch_lightning.plugins.training_type.ddp] 322 - initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
[2022-01-18 16:40:17,469 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:40:17,471 INFO @pytorch_lightning.plugins.training_type.ddp] 322 - initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
[2022-01-18 16:40:18,214 INFO @torch.distributed.distributed_c10d] 196 - Added key: store_based_barrier_key:1 to store for rank: 1
[2022-01-18 16:40:18,222 INFO @torch.distributed.distributed_c10d] 196 - Added key: store_based_barrier_key:1 to store for rank: 0
[2022-01-18 16:40:18,222 INFO @torch.distributed.distributed_c10d] 226 - Rank 0: Completed store-based barrier for 2 nodes.
[2022-01-18 16:40:18,223 INFO @pytorch_lightning.utilities.distributed] 328 - ----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All DDP processes registered. Starting ddp with 2 processes
----------------------------------------------------------------------------------------------------

[2022-01-18 16:40:18,225 INFO @torch.distributed.distributed_c10d] 226 - Rank 1: Completed store-based barrier for 2 nodes.
[2022-01-18 16:40:22,229 INFO @pytorch_lightning.accelerators.gpu] 54 - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
[2022-01-18 16:40:22,230 INFO @pytorch_lightning.accelerators.gpu] 54 - LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
[2022-01-18 16:40:22,230 ERROR @src.logger.base_logger] 25 - The script halted with an error
Traceback (most recent call last):
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/main.py", line 22, in run
    mod.run(args)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/train.py", line 162, in run
    trainer.fit(model, train_loader, valid_loader)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 873, in _run
    self.accelerator.setup(self, model)  # note: this sets up self.lightning_module
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/accelerators/gpu.py", line 42, in setup
    return super().setup(trainer, model)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 88, in setup
    self.setup_optimizers(trainer)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 330, in setup_optimizers
    optimizers, lr_schedulers, optimizer_frequencies = self.training_type_plugin.init_optimizers(
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 223, in init_optimizers
    return trainer.init_optimizers(model)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/optimizers.py", line 34, in init_optimizers
    optim_conf = model.configure_optimizers()
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 323, in configure_optimizers
    optimizer = torch.optim.Adam(self.net.parameters(), lr=self.hparams.lr,
TypeError: __init__() got an unexpected keyword argument 'momentum'
[2022-01-18 16:40:22,230 ERROR @src.logger.base_logger] 25 - The script halted with an error
Traceback (most recent call last):
  File "main.py", line 22, in run
    mod.run(args)
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/train.py", line 162, in run
    trainer.fit(model, train_loader, valid_loader)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 873, in _run
    self.accelerator.setup(self, model)  # note: this sets up self.lightning_module
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/accelerators/gpu.py", line 42, in setup
    return super().setup(trainer, model)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 88, in setup
    self.setup_optimizers(trainer)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 330, in setup_optimizers
    optimizers, lr_schedulers, optimizer_frequencies = self.training_type_plugin.init_optimizers(
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 223, in init_optimizers
    return trainer.init_optimizers(model)
  File "/home/doni-lab-ai/miniconda3/envs/adgan/lib/python3.8/site-packages/pytorch_lightning/trainer/optimizers.py", line 34, in init_optimizers
    optim_conf = model.configure_optimizers()
  File "/home/doni-lab-ai/Documenti/NeuralNetworks/src/mobilenetv3.py", line 323, in configure_optimizers
    optimizer = torch.optim.Adam(self.net.parameters(), lr=self.hparams.lr,
TypeError: __init__() got an unexpected keyword argument 'momentum'
[2022-01-18 16:41:06,946 INFO @src.logger.base_logger] 19 - Running script at src.train
[2022-01-18 16:41:07,865 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:41:07,875 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:41:08,172 DEBUG @src.logger.base_logger] 23 - Detected device: cuda
[2022-01-18 16:41:08,173 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:41:08,173 INFO @src.logger.base_logger] 51 - CuDNN is enabled: True
[2022-01-18 16:41:08,259 INFO @pytorch_lightning.utilities.distributed] 1294 - GPU available: True, used: True
[2022-01-18 16:41:08,259 INFO @pytorch_lightning.utilities.distributed] 1297 - TPU available: False, using: 0 TPU cores
[2022-01-18 16:41:08,259 INFO @pytorch_lightning.utilities.distributed] 1300 - IPU available: False, using: 0 IPUs
[2022-01-18 16:41:08,259 INFO @src.logger.base_logger] 157 - Precision: 32
[2022-01-18 16:41:08,259 INFO @src.logger.base_logger] 158 - Train the mobilenetv3 model.
[2022-01-18 16:41:08,322 INFO @src.logger.base_logger] 19 - Running script at src.train
[2022-01-18 16:41:09,269 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:41:09,281 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:41:09,605 DEBUG @src.logger.base_logger] 23 - Detected device: cuda
[2022-01-18 16:41:09,606 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:41:09,606 INFO @src.logger.base_logger] 51 - CuDNN is enabled: True
[2022-01-18 16:41:09,698 INFO @src.logger.base_logger] 157 - Precision: 32
[2022-01-18 16:41:09,699 INFO @src.logger.base_logger] 158 - Train the mobilenetv3 model.
[2022-01-18 16:41:09,699 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:41:09,700 INFO @pytorch_lightning.plugins.training_type.ddp] 322 - initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
[2022-01-18 16:41:10,041 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:41:10,045 INFO @pytorch_lightning.plugins.training_type.ddp] 322 - initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
[2022-01-18 16:41:10,702 INFO @torch.distributed.distributed_c10d] 196 - Added key: store_based_barrier_key:1 to store for rank: 1
[2022-01-18 16:41:10,702 INFO @torch.distributed.distributed_c10d] 196 - Added key: store_based_barrier_key:1 to store for rank: 0
[2022-01-18 16:41:10,702 INFO @torch.distributed.distributed_c10d] 226 - Rank 1: Completed store-based barrier for 2 nodes.
[2022-01-18 16:41:10,703 INFO @torch.distributed.distributed_c10d] 226 - Rank 0: Completed store-based barrier for 2 nodes.
[2022-01-18 16:41:10,703 INFO @pytorch_lightning.utilities.distributed] 328 - ----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All DDP processes registered. Starting ddp with 2 processes
----------------------------------------------------------------------------------------------------

[2022-01-18 16:41:14,647 INFO @pytorch_lightning.accelerators.gpu] 54 - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
[2022-01-18 16:41:14,647 INFO @pytorch_lightning.accelerators.gpu] 54 - LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
[2022-01-18 16:41:14,718 DEBUG @git.cmd] 869 - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:41:14,878 DEBUG @urllib3.connectionpool] 227 - Starting new HTTP connection (1): localhost:8080
[2022-01-18 16:41:14,884 DEBUG @urllib3.connectionpool] 452 - http://localhost:8080 "POST /graphql HTTP/1.1" 200 464
[2022-01-18 16:41:14,893 DEBUG @urllib3.connectionpool] 227 - Starting new HTTP connection (1): localhost:8080
[2022-01-18 16:41:14,899 DEBUG @urllib3.connectionpool] 452 - http://localhost:8080 "POST /graphql HTTP/1.1" 200 368
[2022-01-18 16:41:18,065 INFO @pytorch_lightning.core.lightning] 1736 - 
  | Name          | Type             | Params
---------------------------------------------------
0 | net           | MobileNetV3      | 4.3 M 
1 | criterion     | CrossEntropyLoss | 0     
2 | train_metrics | MetricCollection | 0     
3 | val_metrics   | MetricCollection | 0     
4 | test_metrics  | MetricCollection | 0     
---------------------------------------------------
4.3 M     Trainable params
0         Non-trainable params
4.3 M     Total params
17.141    Total estimated model params size (MB)
[2022-01-18 16:41:21,226 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:41:21,226 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:48:12,167 INFO @src.logger.base_logger] 19 - Running script at src.train
[2022-01-18 16:48:13,111 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:48:13,122 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:48:13,423 DEBUG @src.logger.base_logger] 23 - Detected device: cuda
[2022-01-18 16:48:13,424 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:48:13,424 INFO @src.logger.base_logger] 51 - CuDNN is enabled: True
[2022-01-18 16:48:13,492 INFO @pytorch_lightning.utilities.distributed] 1294 - GPU available: True, used: True
[2022-01-18 16:48:13,492 INFO @pytorch_lightning.utilities.distributed] 1297 - TPU available: False, using: 0 TPU cores
[2022-01-18 16:48:13,492 INFO @pytorch_lightning.utilities.distributed] 1300 - IPU available: False, using: 0 IPUs
[2022-01-18 16:48:13,492 INFO @src.logger.base_logger] 157 - Precision: 32
[2022-01-18 16:48:13,492 INFO @src.logger.base_logger] 158 - Train the mobilenetv3 model.
[2022-01-18 16:48:13,551 INFO @src.logger.base_logger] 19 - Running script at src.train
[2022-01-18 16:48:14,514 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:48:14,524 DEBUG @git.cmd] 869 - Popen(['git', 'version'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:48:14,833 DEBUG @src.logger.base_logger] 23 - Detected device: cuda
[2022-01-18 16:48:14,834 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:48:14,834 INFO @src.logger.base_logger] 51 - CuDNN is enabled: True
[2022-01-18 16:48:14,902 INFO @src.logger.base_logger] 157 - Precision: 32
[2022-01-18 16:48:14,902 INFO @src.logger.base_logger] 158 - Train the mobilenetv3 model.
[2022-01-18 16:48:14,903 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:48:14,904 INFO @pytorch_lightning.plugins.training_type.ddp] 322 - initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
[2022-01-18 16:48:15,273 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:48:15,277 INFO @pytorch_lightning.plugins.training_type.ddp] 322 - initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
[2022-01-18 16:48:15,905 INFO @torch.distributed.distributed_c10d] 196 - Added key: store_based_barrier_key:1 to store for rank: 1
[2022-01-18 16:48:15,915 INFO @torch.distributed.distributed_c10d] 196 - Added key: store_based_barrier_key:1 to store for rank: 0
[2022-01-18 16:48:15,915 INFO @torch.distributed.distributed_c10d] 226 - Rank 0: Completed store-based barrier for 2 nodes.
[2022-01-18 16:48:15,915 INFO @pytorch_lightning.utilities.distributed] 328 - ----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All DDP processes registered. Starting ddp with 2 processes
----------------------------------------------------------------------------------------------------

[2022-01-18 16:48:15,916 INFO @torch.distributed.distributed_c10d] 226 - Rank 1: Completed store-based barrier for 2 nodes.
[2022-01-18 16:48:20,083 INFO @pytorch_lightning.accelerators.gpu] 54 - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
[2022-01-18 16:48:20,084 INFO @pytorch_lightning.accelerators.gpu] 54 - LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
[2022-01-18 16:48:20,153 DEBUG @git.cmd] 869 - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/doni-lab-ai/Documenti/NeuralNetworks, universal_newlines=False, shell=None, istream=None)
[2022-01-18 16:48:20,300 DEBUG @urllib3.connectionpool] 227 - Starting new HTTP connection (1): localhost:8080
[2022-01-18 16:48:20,308 DEBUG @urllib3.connectionpool] 452 - http://localhost:8080 "POST /graphql HTTP/1.1" 200 464
[2022-01-18 16:48:20,316 DEBUG @urllib3.connectionpool] 227 - Starting new HTTP connection (1): localhost:8080
[2022-01-18 16:48:20,322 DEBUG @urllib3.connectionpool] 452 - http://localhost:8080 "POST /graphql HTTP/1.1" 200 368
[2022-01-18 16:48:23,492 INFO @pytorch_lightning.core.lightning] 1736 - 
  | Name          | Type             | Params
---------------------------------------------------
0 | net           | MobileNetV3      | 1.5 M 
1 | criterion     | CrossEntropyLoss | 0     
2 | train_metrics | MetricCollection | 0     
3 | val_metrics   | MetricCollection | 0     
4 | test_metrics  | MetricCollection | 0     
---------------------------------------------------
1.5 M     Trainable params
0         Non-trainable params
1.5 M     Total params
6.085     Total estimated model params size (MB)
[2022-01-18 16:48:26,680 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 16:48:26,680 INFO @pytorch_lightning.utilities.seed] 65 - Global seed set to 1234
[2022-01-18 17:11:54,736 DEBUG @urllib3.connectionpool] 227 - Starting new HTTP connection (1): localhost:8080
[2022-01-18 17:11:54,745 DEBUG @urllib3.connectionpool] 452 - http://localhost:8080 "POST /graphql HTTP/1.1" 200 58
[2022-01-18 17:11:54,780 INFO @pytorch_lightning.profiler.base] 113 - FIT Profiler Report

Action                             	|  Mean duration (s)	|Num calls      	|  Total time (s) 	|  Percentage %   	|
--------------------------------------------------------------------------------------------------------------------------------------
Total                              	|  -              	|_              	|  1421.3         	|  100 %          	|
--------------------------------------------------------------------------------------------------------------------------------------
run_training_epoch                 	|  28.149         	|50             	|  1407.5         	|  99.03          	|
run_training_batch                 	|  0.16201        	|5900           	|  955.86         	|  67.255         	|
model_forward                      	|  0.1563         	|5900           	|  922.17         	|  64.884         	|
training_step                      	|  0.1562         	|5900           	|  921.58         	|  64.843         	|
closure_0                          	|  0.11165        	|5900           	|  658.76         	|  46.351         	|
get_train_batch                    	|  0.033206       	|5900           	|  195.92         	|  13.785         	|
training_batch_to_device           	|  0.0086344      	|5900           	|  50.943         	|  3.5843         	|
evaluation_step_and_end            	|  0.041977       	|1002           	|  42.061         	|  2.9594         	|
validation_step                    	|  0.041892       	|1002           	|  41.975         	|  2.9534         	|
evaluation_batch_to_device         	|  0.0084748      	|1002           	|  8.4917         	|  0.59748        	|
on_train_batch_end                 	|  0.00020896     	|5900           	|  1.2329         	|  0.086746       	|
on_train_epoch_end                 	|  0.0070569      	|50             	|  0.35284        	|  0.024826       	|
on_after_backward                  	|  4.3482e-05     	|5900           	|  0.25655        	|  0.018051       	|
on_before_optimizer_step           	|  3.1957e-05     	|5900           	|  0.18854        	|  0.013266       	|
on_validation_batch_end            	|  0.00018263     	|1002           	|  0.18299        	|  0.012875       	|
on_before_backward                 	|  2.8283e-05     	|5900           	|  0.16687        	|  0.011741       	|
on_batch_start                     	|  2.7738e-05     	|5900           	|  0.16366        	|  0.011515       	|
on_train_batch_start               	|  2.3316e-05     	|5900           	|  0.13756        	|  0.009679       	|
training_step_end                  	|  2.0878e-05     	|5900           	|  0.12318        	|  0.0086669      	|
on_batch_end                       	|  1.9406e-05     	|5900           	|  0.1145         	|  0.0080559      	|
on_validation_end                  	|  0.0016235      	|51             	|  0.082799       	|  0.0058258      	|
on_validation_start                	|  0.00068269     	|51             	|  0.034817       	|  0.0024497      	|
on_validation_batch_start          	|  3.0743e-05     	|1002           	|  0.030804       	|  0.0021674      	|
on_train_epoch_start               	|  0.00059281     	|50             	|  0.02964        	|  0.0020855      	|
validation_step_end                	|  1.6223e-05     	|1002           	|  0.016255       	|  0.0011437      	|
on_epoch_end                       	|  3.372e-05      	|101            	|  0.0034057      	|  0.00023963     	|
on_train_start                     	|  0.0030774      	|1              	|  0.0030774      	|  0.00021652     	|
on_validation_epoch_end            	|  5.1857e-05     	|51             	|  0.0026447      	|  0.00018608     	|
on_epoch_start                     	|  2.4314e-05     	|101            	|  0.0024557      	|  0.00017278     	|
on_validation_epoch_start          	|  2.03e-05       	|51             	|  0.0010353      	|  7.2845e-05     	|
on_train_end                       	|  0.00038594     	|1              	|  0.00038594     	|  2.7155e-05     	|
on_fit_start                       	|  4.7937e-05     	|1              	|  4.7937e-05     	|  3.3729e-06     	|
on_val_dataloader                  	|  2.1709e-05     	|1              	|  2.1709e-05     	|  1.5275e-06     	|
on_train_dataloader                	|  1.9031e-05     	|1              	|  1.9031e-05     	|  1.339e-06      	|
on_before_accelerator_backend_setup	|  8.3498e-06     	|1              	|  8.3498e-06     	|  5.8749e-07     	|

